### ISSUE TITLE
프로젝트 세팅 / CICD 구축

### ISSUE THREAD

**Issue by kweonsikyung** [Link-Cargo/link-cargo-front#3]
## 🗓️ Due date
07/16

## 🌈 Feature List
- [x] next 프레임워크 프로젝트 세팅 @kweonsikyung 
- [x] 서버 호스팅 및 cicd 구축 @YPYP333YPYP @donghyuun 

## ✅ Check List

- [x] !!트렐로 카드 등록
- [x] 담당자 등록
- [x] 라벨 등록 `EPIC`
- [x] DDL 체크
