### ISSUE TITLE
메인화면 UI 구현

### ISSUE THREAD

**Issue by kweonsikyung** [Link-Cargo/link-cargo-front#9]
## 📌 어떤 EPIC/Milestone 인가요?
메인화면 UI 구현

## 🗓️ Due date
7/24

## 🌈 Feature List
- [x] 메인화면 UI 구현

## ✅ Check List

- [x] !!트렐로 카드 등록
- [x] 담당자 등록
- [x] 라벨 등록 `EPIC`
- [x] DDL 체크
